#!/usr/bin/env bash

if
  [[ -s "/Users/edsonma/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/environment" ]]
then
  source "/Users/edsonma/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/edsonma/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/environment'" >&2
  exit 1
fi
