abbr origem "cd ~/workspace/workspace-origem/projects; ls"
abbr personal "cd ~/workspace/workspace-personal/; ls"
abbr work "cd ~/workspace; ls"
abbr chuva "curl -4 http://wttr.in/Brasilia"
abbr ip "tools/./ip.sh"
abbr vqf "cd /Users/edsonma/workspace/workspace-music/vqf"
abbr lilyponding "cd /Users/edsonma/workspace/workspace-unb/talks/lilypond_music_talks; ls"
abbr rd "cd /Users/edsonma/workspace/workspace-rdstation; ls"
abbr rdsm "cd /Users/edsonma/workspace/workspace-rdstation/projects/rdstation; ls"
abbr clustering "cd /Users/edsonma/workspace/workspace-rdstation/projects/clustering-engine; ls"
abbr cpu "sudo powermetrics --samplers smc |grep -i \"CPU die temperature\""
abbr gpu "sudo powermetrics --samplers smc |grep -i \"GPU die temperature\""
abbr metrics "sudo powermetrics | sed -n '/\*\*\*\* SMC sensors \*\*\*\*/,/Number of prochots/p'"
abbr system "system_profiler SPSoftwareDataType"
abbr fucking_ip "curl wtfismyip.com/json"
abbr s "docker compose config | yq '.services[]|key'"
abbr g "git"
abbr ga "git add"
abbr gall "git add --all"
abbr gc "git commit"
abbr gb "git branch"
abbr gp "git pull"
abbr gsh "git push"
abbr gpr "git pull --rebase"
abbr gco "git checkout"
abbr gcb "git checkout -b"
abbr gl "git log"
abbr gd "git diff"
abbr gs "git status"
abbr gfa "git fetch --all"
abbr grc "git rebase --continue"
abbr gra "git rebase --abort"
abbr vqf "cd /Users/edsonma/workspace/workspace-music/vqf"
abbr rvim 'vim -u  ~/dotfiles/vim/railsrc'
abbr gvim 'vim -u  ~/dotfiles/vim/vimrc'
abbr zs "zookeeper-server-start /usr/local/etc/zookeeper/zoo.cfg&"
abbr ks "kafka-server-start /usr/local/etc/kafka/server.properties&"
abbr ze "zookeeper-server-stop /usr/local/etc/zookeeper/zoo.cfg&"
abbr ke "kafka-server-stop /usr/local/etc/kafka/server.properties&"
abbr kraft "kafka-server-start /usr/local/etc/kafka/kraft/server.properties&"
abbr krafte "kafka-server-stop /usr/local/etc/kafka/kraft/server.properties&"


