abbr training "cd ~/workspace/training/; ls"
abbr projects "cd ~/workspace/workspace-projects/; ls"
abbr work "cd ~/workspace; ls"
abbr chuva "curl -4 http://wttr.in/Brasilia"
abbr ip "tools/./ip.sh"
abbr vqf "cd /Users/edsonma/workspace/workspace-music/vqf"
abbr lilyponding "cd /Users/edsonma/workspace/workspace-unb/talks/lilypond_music_talks; ls"
abbr rd "cd /Users/edsonma/workspace/workspace-rdstation; ls"
abbr rdsm "cd /Users/edsonma/workspace/workspace-rdstation/projects/rdstation; ls"
abbr clustering "cd /Users/edsonma/workspace/workspace-rdstation/projects/clustering-engine; ls"
abbr cpu "sudo powermetrics --samplers smc |grep -i \"CPU die temperature\""
abbr gpu "sudo powermetrics --samplers smc |grep -i \"GPU die temperature\""
abbr metrics "sudo powermetrics | sed -n '/\*\*\*\* SMC sensors \*\*\*\*/,/Number of prochots/p'"
abbr system "system_profiler SPSoftwareDataType"
abbr fucking_ip "curl wtfismyip.com/json"

