#!/usr/bin/env bash

if
  [[ -s "/Users/edsonma/.rvm/gems/ruby-3.1.0/environment" ]]
then
  source "/Users/edsonma/.rvm/gems/ruby-3.1.0/environment"
  exec dotenv "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/edsonma/.rvm/gems/ruby-3.1.0/environment'" >&2
  exit 1
fi
